#!/bin/sh
exec >/dev/null 2>&1

xrandr --setprovideroutputsource nvidia iGPU
xrandr --auto
xrandr --output eDP-1-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI-0 --mode 1920x1080 --right-of eDP-1-1 --rotate normal --dpi 100

# syncthing --no-browser &
# kmonad ~/.config/kmonad.kbd &
scrond -f ~/.config/cron/crontab

exec dbus-run-session -- dwm
